# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

before_all do
  setup_semaphore
end

lane :beta do
  app_store_connect_api_key(
    key_id: "ACRT8F65H9",
    issuer_id: "6053b7fe-68a8-4acb-89be-165aa6465141",
    key_filepath: "/Users/juniorfernandes/Documents/shopper/teste-ci/fastlane/AuthKey_ACRT8F65H9.p8"
  )

  build_app(
    scheme: "TallestTowers"
  )

  firebase_app_distribution(
    app: "1:514783791039:ios:71fe19c388ef46dc37830a",
    groups: "iOS-QA",
    release_notes: "Versão beta com novos recursos e correções de bugs.",
    debug: true,
    firebase_cli_token: "1//01k0TqGBmY-KtCgYIARAAGAESNwF-L9IrLEyT6i0oBJ3wQC2qrppKvtLOkJ6te6X__KgLovBFs9lZho2SZiDvW6uWuy8MQjhX8zA",
    service_credentials_file: "/Users/juniorfernandes/Downloads/api-key.json"
  )
end

lane :deploy_to_testflight do
  app_store_connect_api_key(
    key_id: "ACRT8F65H9",
    issuer_id: "5869ed4d-ecb1-4bec-a7e8-7a114d5d1a31",
    key_filepath: "/Users/juniorfernandes/Documents/shopper/teste-ci/fastlane/AuthKey_ACRT8F65H9.p8"
  )

  get_certificates
  get_provisioning_profile
  get_provisioning_profile(app_identifier: "com.teste-ci.shopper")

  build_app(
    scheme: "TallestTowers", export_xcargs: "-allowProvisioningUpdates"
  )

  upload_to_testflight(
    expire_previous_builds: true,
  )

  upload_to_app_store(
    skip_screenshots: true,
    skip_metadata: true,
    app_identifier: "com.teste-ci.shopper",
    submit_for_review: false,
    team_id: "N8AN855MLL",
    release_notes: {
      "en-US" => "Release notes for this version.",
      "pt-BR" => "Notas de lançamento para esta versão."
    }
  )
end

lane :get_current_build_number do
  current_build_number = get_build_number
  puts "Número atual da build: #{current_build_number}"
end

lane :increment_build do
  current_build_number = get_build_number
  puts "Número atual da build: #{current_build_number}"
  increment_build_number
  new_build_number = get_build_number
  puts "Novo número da build: #{new_build_number}"
end


lane :release do
  api_key = app_store_connect_api_key(
    key_id: "ACRT8F65H9",
    issuer_id: "6053b7fe-68a8-4acb-89be-165aa6465141",
    key_filepath: "/Users/juniorfernandes/Documents/shopper/teste-ci/fastlane/AuthKey_ACRT8F65H9.p8",
    duration: 1200,
    in_house: false
  )

  pilot(api_key: api_key)
end

lane :tests do
  run_tests(scheme: "TallestTowers")
end

platform :ios do
  lane :build do
    match(type: 'adhoc')
    gym(scheme: 'TallestTowers', clean: true)
  end

  lane :test do
    run_tests(scheme: 'TallestTowers', devices: ['iPhone 11 Pro'], prelaunch_simulator: true)
  end

  lane :screenshots do
    snapshot
  end
end
